menu:
  img: /u/base/logo.svg
  items:
  - url: /
    label: Inicio
    icon: home
  - url: /#nosotros
    label: Nosotros
    icon: info
  # - url: /#equipo
  #   label: Equipo
  #   icon: groups_3
  - url: /#proyectos-destacados
    label: Destacados
    icon: crown
  - url: /#productos
    label: Productos
    icon: web_stories
    items:
    - url: /productos/envolvente/
      label: Envolvente
      icon: window_closed
    - url: /productos/proteccion-solar/
      label: Protección Solar
      icon: blinds
    - url: /productos/interiorismo/
      label: Interiorismo y Decoración
      icon: family_home
  - url: /#nos-caracteriza
    label: Nos Caracteriza
    icon: star
  # - url: /#taller
  #   label: Taller
  #   icon: construction
  - url: /#marcas
    label: Marcas
    icon: verified
  # - url: /#certificaciones
  #   label: Certificaciones
  #   icon: verified
  # - url: /#aliados
  #   label: Aliados
  #   icon: handshake
  - url: /#resenas
    label: Reseñas
    icon: reviews
  - url: /#contacto
    label: Contacto
    icon: send
    btn: cta
footer:
  dots:
  - url: https://g.page/r/CSUgV5RIKLWvEAg
  - url: https://instagram.com/eurolux_srl
  - url: https://www.linkedin.com/company/eurolux-srl/people/
  - url: https://www.youtube.com/channel/UC-78JinGgWYkz6KG4T69qjw
