title: Productos
subtitle: Dise침o, Fabricaci칩n e Instalaci칩n
color: light
size: md
icon: rectangle-vertical-history
bg: eurolux.mp4
more:
  opacity: 30
  parallax: true
rows:
- type: columns
  design:
    color: white
  items:
  - title: Envolvente
    link: /#envolvente
    icon: window-frame
  - title: Protecci칩n Solar
    link: /#proteccion-solar
    icon: shutters
  - title: Interiorismo
    link: /#interiorismo
    icon: house-heart
