id: interiorismo
title: Interiorismo y Decoración
subtitle: Diseño, Fabricación e Instalación
size: md
icon: house-heart
more:
  container: light
rows:
- type: columns
  design:
    num: 3
    color: main-light
  items:
  - title: En Construcción
    icon: triangle-person-digging
