title: Envolvente
subtitle: Dise침o, Fabricaci칩n e Instalaci칩n
size: md
icon: window-frame
more:
  container: light
rows:
- type: columns
  design:
    num: 3
    color: white
    inset: true
    ratio: 3x2
  items:
  - title: Vidrios Control Solar
    link: /vidrios-control-solar/
    image: envolvente/vidrios-control-solar/1.jpg
  - title: Ventanas y Puertas Correderas
    link: /ventanas-puertas-correderas/
    image: envolvente/ventanas-puertas-correderas/1.jpg
  - title: Puertas de Garaje
    link: /puertas-garaje/
    image: envolvente/puertas-garaje/1.jpg
  - title: Mamparas de Ba침o
    link: /mamparas-bano/
    image: envolvente/mamparas-bano/1.jpg
  - title: Louvers
    link: /louvers/
    image: envolvente/louvers/1.jpg
  - title: Techos de Vidrio
    link: /techos-vidrio/
    image: envolvente/techos-vidrio/1.jpg
  - title: Barandas
    link: /barandas/
    image: envolvente/barandas/1.jpg
  - title: Puertas y Ventanas Abatibles
    link: /puertas-ventanas-abatibles/
    image: envolvente/puertas-ventanas-abatibles/1.jpg
  - title: Ventanas Oscilo-Batientes
    link: /ventanas-oscilo-batientes/
    image: envolvente/ventana-oscilo-batiente/apertura-batiente.jpg
